### PR TITLE
LoginWebViewController:  rebuild navigationBar title and cancel, and use rangeOfString: to find dest string.

### PR DESCRIPTION
**Pull request by Jonwei**
**1. embed in a UINavigationController to show title and backButton.
2. use weak-strong reference in block
3. find key string in response sting: first separate string to array, then try to find the dest string. hence, don't need to the dest string length.
**
MoreViewController:
1. use weak-strong reference in block
2. create a UINavigationController to contain LoginWebViewController

### CODE REVIEW

**Comment by coderyi** [comment]
What does it mean?

**Comment by coderyi** [comment]
I found I could not run this feature，and i hope the backbutton has a image

**Comment by Jonwei** [comment]
@coderyi  
1. could not run this feature ? do you merge these codes to your local branch ? suggest a create a new develop branch to merge new feature to test. 
2. I tried to use "ic_arrow_back_white_48pt", and the image is too big to show in iOS9.2 simulator. Anyway, I will try it.

**Comment by Jonwei** [comment]
@coderyi use "ic_arrow_back_white_24pt" replacing "ic_arrow_back_white_48pt". 
[Apple office Human Interface Guidelines](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW1)

loginui

how about the new login UI ? If OK, I will create a new pull request.

**Pull request closed without merging**
